### ISSUE TITLE
Unable to submit

### ISSUE THREAD

**Issue by Kf637** [saul-avikar/discord-application-bot#4]
userToSubmitApplicationsTo.send(
^
TypeError: userToSubmitApplicationsTo.send is not a function
at applicationFormCompleted (/app/index.js:22:30)
at Client.client.on.msg (/app/index.js:194:13)
at Client.emit (events.js:189:13)
at MessageCreateAction.handle (/rbd/pnpm-volume/4120c502-bd19-4532-a4fc-5249062306e5/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
at Object.module.exports [as MESSAGE_CREATE] (/rbd/pnpm-volume/4120c502-bd19-4532-a4fc-5249062306e5/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
at WebSocketManager.handlePacket (/rbd/pnpm-volume/4120c502-bd19-4532-a4fc-5249062306e5/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
at WebSocketShard.onPacket (/rbd/pnpm-volume/4120c502-bd19-4532-a4fc-5249062306e5/node_modules/discord.js/src/client/websocket/WebSocketShard.js:436:22)
at WebSocketShard.onMessage (/rbd/pnpm-volume/4120c502-bd19-4532-a4fc-5249062306e5/node_modules/discord.js/src/client/websocket/WebSocketShard.js:293:10)
at WebSocket.onMessage (/rbd/pnpm-volume/4120c502-bd19-4532-a4fc-5249062306e5/node_modules/ws/lib/event-target.js:125:16)
at WebSocket.emit (events.js:189:13)
![90131415-63df3380-dd6c-11ea-8484-790514838ac6](https://user-images.githubusercontent.com/43268197/90151512-1623f480-dd87-11ea-9192-556532855941.png)

**Comment by Jordaar** [comment]
**This bot is dead and old**

**Comment by Plu-sys** [comment]
Which version is it on ?

**Comment by saul-jb** [comment]
Fixed  8c69c2b.
